name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '10', '8' ]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '10.16.3'
    - name: install dependecies
      run: |
        npm ci
        npm run build --if-present
    - name: run the tests
      run: 'npm test -- --coverage'
      env:
        CI: true
        ti2-travelgate-apiKey: '8626cf56-e364-4fd1-4fe0-311e23ac6355'
        ti2-travelgate-client: 'client_demo'
        ti2-travelgate-endpoint: 'https://api.travelgatex.com'
